### PR TITLE
Fix missing "#" in a list of characters

### PR DESCRIPTION
**Pull request by spainisnotequal**
Just spotted what looks like a typo. I guess the intention is to loop over a list of characters, so the list should be `'(#\a #\b #\c #\d)` instead of `'(#\a \b #\c #\d)`.

### CODE REVIEW

**Comment by phoe** [comment]
Correct! Thank you for fixing the bug. I've missed it while rewriting the koans.

**Comment by spainisnotequal** [comment]
You’re Welcome! I'm working on the koans right now (though not regularly), so I'll let you know if I spot any additional typo.

I'm at 111 out of 199 koans right now, and just found two very small typos, so you have made a fantastic job. Congratulations, and thanks for the your time and effort!

**Comment by phoe** [comment]
Thanks as well! Every little PR like this makes the koans an even better resource. :heart:

**Comment by phoe** [comment]
@Slids This is ready for merging.

**Comment by phoe** [comment]
Oh! Hold on a second

@spainisnotequal Could you also fix the solution in https://github.com/google/lisp-koans/blob/master/koans-solved/loops.lisp ?

**Comment by spainisnotequal** [comment]
Done!

**Pull request merged**
