### PR TITLE
Fix #116

### LINKED ISSUE #116: condition-handlers always error
in `koans/ondition-handlers.lisp`, koans always signals an error, for example
```lisp
(define-test handler-bind
  ;; When a condition is signaled, all handlers whose type matches the
  ;; condition's type are allowed to execute.
  (let ((*list* '()))
    (handler-bind ((my-error #'handle-my-error)
                   (error #'handle-error)
                   (my-serious-condition #'handle-my-serious-condition))
      (signal (make-condition 'my-error)))
    (assert-equal '( :error :my-error) *list*)))
```
this is solved in  `koans-solved/condition-handlers.lisp`

### PR DESCRIPTION
**Pull request by phoe**

### CODE REVIEW

**Comment by Slids** [comment]
Why change something, error, serious-error to foo, bar, baz?

**Comment by phoe** [comment]
We are signaling an `error` in the previous version. It triggers the test framework into thinking that there was an unhandled error (since `handler-bind` does not transfer control), which fails the koan.

**Comment by Slids** [comment]
Okay, but that doesn't answer my question.

**Comment by phoe** [comment]
Because `my-condition` is not of type `error`, `serious-condition`, `my-error`, or `my-serious-condition`. Unless we change them, we are going to have handlers that are never going to fire when `my-condition` is signaled, which makes these koans meaningless.

**Comment by Slids** [comment]
But why not like:

(define-condition y--error () ())

(define-condition serious-error (merror) ())

(define-condition super-duper-serious-error (serious-error) ())

Why use the words foo, bar, and baz?

**Comment by Slids** [comment]
/sigh, my question is why do we use the terms foo bar and baz.
Theoretically there is a better worded moniker to give to them...

**Comment by phoe** [comment]
I see now, OK. We could name these in some kinda-meaningful way - like `silly-condition`, `very-silly-condition` and `absolutely-silly-condition`. What do you think of that?

`(define-condition merror () ())` would be a semantic error, because `merror` is named after `error` but does not inherit from it.

**Comment by Slids** [comment]
Ah my shitty typos... But yes those names sound okay.

**Comment by phoe** [comment]
OK - how does it look now?

**Comment by Slids** [comment]
lgtm, just to make sure, you tested it?

**Comment by phoe** [comment]
Yep. Re-ran the full tests, too, and also fixed one `loop` issue not caught by #115.

**Comment by Slids** [comment]
Thank you!
I really appreciate your work here, and I REALLY look forward to your book.

**Pull request merged**
